### PR TITLE
#58 Test that the code properly handles multiple columns

### PR DESCRIPTION
**Pull request by bancona**
See [this issue](https://github.com/codeforboston/flagging/issues/58) for details.

### CODE REVIEW

**Comment by dwreeves** [comment]
Wow! Very fast turnaround, and excellent job on this; this isn't a simple task and it's extra impressive as a first-contribution. Also, bonus points for PEP8ing the order of the import statements via putting `import pandas as pd` above the flagging_site module imports-- I see that and appreciate that!

I'll be able to run this later tonight, but it looks really good and looks like it'll run. I do not believe I will have any additional. comments or feedback if this works.

One small thing, and I hate to be super nitpicky about this: We agreed a while ago to use single-quoted strings (for non-docstrings): https://github.com/codeforboston/flagging/wiki/Code-Style-Guide#1-use-pep-8

**Comment by bancona** [comment]
Nitpicky is good! I definitely appreciate learning best practices, especially since I'm new to Python 3 (from 2.7). Just updated the strings to use single quotes

**Comment by dwreeves** [comment]
As a note so I don't confuse you: neither single nor double by itself is a best practice-- the best practice is being consistent within a project directory.

**Comment by ryxcommar** [comment]
LGTM!

image

**Comment by dwreeves** [comment]
LGTM!

image

**Pull request merged**
