### PR TITLE
Replaced HTTPException(status_code) with abort(status_code)

### PR DESCRIPTION
**Pull request by LewisStaples**
HTTPException(status_code) has been replaced with abort(status_code)

### CODE REVIEW

**Comment by dwreeves** [comment]
LGTM. I would suggest using an f-string instead of adding strings with `+`, but it's not at all a big deal. Something like this:

```python
error_message = f"link has failed with error # {res.status_code}"
```

If you want to make that change then cool-- otherwise, I'll pull this on Friday as-is.

Thank you for your contribution!

**Comment by dwreeves** [comment]
LGTM.

**Comment by LewisStaples** [comment]
Daniel,  Thank you for the suggestion to switch to an f-string.  I have an issue that blocks me from switching to an f-string, and I have decided not to do this.  Read on below if you want to know why .....

I am able to test the exception versus abort (there is probably a better way to do it, but my way is to manually change the hobolink to force an error).

When I wrote the abort call on Wednesday night, my error tests were displaying my message in the browser.

Now (on Thursday night), my error tests do not display my written message .... instead I am getting a string describing the error.  For example, the webpage with a 405 error gives a webpage created with the below HTML markup.  Anyhow, I've spent more time than I intended trying to figure out why this changed so I'm just going to go on to consider other things.  Besides, this functionality is nice.

<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

**Comment by dwreeves** [comment]
For testing `abort`, I would just type stuff into a Python terminal like `abort(404, "hello world")` and see what happens. It's not the most formal thing in the world as far as testing goes, but it's just one pre-made function from a stable/well-done/popular library, so its behavior should be very consistent. The expected behavior of `flask.abort` is that it should raise an error, specifically a `werkzeug.exceptions.HTTPException`, if I recall correctly.

I'm not 100% sure if I understand your issue, but I think there are two things that are possible:

- If you mean that your browser is displaying something differently than it was before: In Flask, if you are in debug mode, the browser displays the full error message. But if you are _not_ in debug mode, it doesn't show you anything.

  If you deploy the website through the `run_windows_dev` or `run_unix_dev` scripts, you'll see something like this in there: `set FLASK_ENV=development` (that's the Windows one at least). What that does is it means that we will eventually run into this code inside of `app.py`:

```python
def create_app(config: Type = None) -> Flask:
    # ...
    # ...
    elif app.env == 'development':
        from .config import DevelopmentConfig
        app.config.from_object(DevelopmentConfig)
```

  So if the environment is `development`, it runs that. And the `DevelopmentConfig` object has the following in it: `DEBUG: bool = True`. Flask is smart, and knows this means to turn debug mode on when it's in the config for the app. However, if you do not deploy through this whole system, then Flask won't do development mode, and this changes how your browser displays errors.

- If you mean that the actual object itself is a string instead of an error: it's a bit misleading how Exceptions work in Python sometimes, but you can see here that what's being returned is an error, even though it kinda looks like a string because of how Python represents it.

```python
>>> try:
>>>     1 / 0
>>> except ZeroDivisionError as e:
>>>:     # Is this a string?
>>>:     print('Print:', e)  # <-- 
>>>     # It kinda looks like a string, so it must be, right?
>>>     # Let's check:
>>>     print('Type: ', type(e))
>>>     # It is not. Errors/Exceptions just represent like that in Python.
>>>     # There is a string you can access though:
>>>     print(e.args, type(e.args[0]))
Print: division by zero
Type:  <class 'ZeroDivisionError'>
('division by zero',) <class 'str'>
```

**Comment by dwreeves** [comment]
Also, I quickly deleted my comment about the f-string because I don't think it's necessary. Adding a string is acceptable in this situation and it's perfectly 100% legible. You're good! I'm merging everyone's code this weekend. Thanks for your help.

**Pull request merged**
