### PR TITLE
parameterized api with flask.request two parameters hour and reach

### PR DESCRIPTION
**Pull request by cameronreaves**
this is a better way to do the api paremterization....but I'm not sure what the hour param does? any help?

### CODE REVIEW

**Comment by dwreeves** [comment]
Hours should return the number of rows of data (each row = 1 hour). The preprocessed dataframe's order is guaranteed to be ascending by timestamp, and each `model` function has a `rows=?` kwarg that handles the number of rows/hours.

Also, `hours` can have a default, it doesn't need to be `None`. So: `hours: int = 48`.

The reason why we want a default for that but not the reaches list is because `= None` is basically necessary for mutable objects like `list`s, but not for basic datatypes like `int`s. This is not to say there are never going to be scenarios where you want `some_integer: int = None`, but those should be instances in which the input is both (1) optional, and (2) either there is no sensible default, or a non-input (i.e. None) represents something distinct from an input of any integer (e.g. -1, 0, and 1 are distinct from a genuine None).

Also in the hypothetical scenario when you want optional integer arguments with default value `None`, you would _not_ want to use the `or` operator: you'd want to do `some_integer is None`. The `or` operator works as a quick shorthand for skipping past `None` defaults when looking at dicts and lists (assuming you also want to skip over empty lists and empty dicts as well, since those have a `bool` value of `False`), but the issue is `some_integer or 5` will return 5 when `some_integer` is 0, even if 0 is a valid input. So in order to avoid that scenario you need to do `if some_integer is None: ...` or `if some_integer is not None: ...` to treat None's differently than 0's.

Sorry, bit of a tangent. TLDR use `hours: int = 48` to set the defaults. Just wanted you to understand what the logic is behind all this because I know it seems like I'm being contradictory about when to use `None` and when not to.

Also, for now, let's set a limit of 48 hours. If someone inputs 49, we should coerce the input down to no more than 48 hours. We should also coerce inputs to be no _fewer_ than 1 hours. (Stuff gets funky when people input negative integers.) We want to extend beyond a 48 hour cap when we're saving more data, ideally we don't want to limit users this hard, but for now I don't think we even have more than 48 hours of USGS data at a time.

**Comment by cameronreaves** [comment]
Thank you! I feel like I am learning a lot through these comments.

**Comment by dwreeves** [comment]
I hope so!

A lot of this stuff is very specific to how Python works and may not carry over to other languages. If you plan on sticking with Python for the long term then this is all important information in my opinion, but it's maybe not so important if you're looking to stick with something else as your primary language.

Anyway, I'll be able to look at your code changes after work, bit busy at the moment. Thank you for your contributions!

**Comment by dwreeves** [comment]
LGTM.

**Pull request merged**
