### PR TITLE
Dev restful

### PR DESCRIPTION
**Pull request by cameronreaves**

### CODE REVIEW

**Comment by dwreeves** [comment]
This is excellent work!

So, this is 100% fault and I should have communicated it clearer, but: I don't think the API should be a _replacement_ of the output tables page; I think both of them should coexist. What I was trying to communicate is that the `output_model` function should be refactored to use the same functions to retrieve data so we don't duplicate code.

The reason why we should have both is because the Rest API and the HTML tables serve two different purposes:

- The API is for building tools on top of it in a raw, easy-to-use format, such as a Javscript widget they can stick on their main website or for researchers who want to access the CRWA's data.

- The HTML tables is for anyone who just wants to visualize the history of the model in a visually appealing and easy to read format.

I think the API can be routed to `/api/v1/model`. (The reason we want `v1` is in case we ever need to change the API schema, we can do so without breaking other people's dependencies. The tricky part about writing public code is once people start using it, it's hard to make changes to it. Tacking `v1` to it is a good way to ensure againt possible future issues.). `/output_model` can be the HTML tables.

Again, this is my fault and I'm sorry for the miscommunication. If you want to reinstate the `output_model` function, you can do so. Otherwise it's no worries and I can add it back in.

None of this is to detract from how awesome this is, though. Reinstating already written code isn't hard; writing code from scratch is the harder part!

I'll have more time to review this in detail later today and I do have a few comments, but based on a skim it looks good.

**Comment by cameronreaves** [comment]
Wow, thanks for the detailed comments. Learned a lot! Let me know if there is anything else.

**Comment by dwreeves** [comment]
No problem! I just need to know (1) if you are able to work on these things, and (2) if so, when you'd expect the changes to be in by. There is no rush; take as much time as you need 😄 I just need to plan based around when this can get implemented.

Thank you!

**Comment by dwreeves** [comment]
I see your new contributions. Nice stuff! I'll take a look at them and try to run it on `localhost`, but looks like it'll work. Thank you so much!

**Comment by dwreeves** [comment]
LGTM!

**Comment by cameronreaves** [comment]
Yay!

**Pull request merged**
