### PR TITLE
flasgger doc

### PR DESCRIPTION
**Pull request by edsun123**
added a line in app.py for swagger and added reachapi.yml inside blueprints. (edited the requirements.txt also)

### CODE REVIEW

**Comment by dwreeves** [comment]
1. Hate to do this to you but ... can you redo this with the latest version of the `dev_restful` branch? The new `dev_restful` branch is very different than this.
2. When you do this, can you wrap not the _app_ but the API _blueprint_ with the Flasgger instance?
3. Pass this kwarg into the Flasgger instance after you've attached it to the API blueprint: `config={'specs_route': '/docs/'}` This will mean the final route will be `/api/docs`.

**Comment by edsun123** [comment]
I've been looking into wrapping flasgger with each blueprint instance instead the whole app. However, swagger seems to need to have access to a config attribute which only the app instance has.
Screen Shot 2020-06-24 at 5 38 21 PM

**Comment by edsun123** [comment]
To resolve the issue:
1) now working on restful_dev branch instead
2) we are using the app instance instead of the blueprint instance. (swagger object needs to be made in the app.py)
3) using config={'specs_route': '/docs/'} does not work unless merge = True because merge copies and add the new config to the default config. However, the merge variable that you find in the master branch cannot be found the release version 0.9.4 because master version is 3 months ago while the release version is since the beginning of the year.

**Comment by edsun123** [comment]
I'm going to close this pull request. I'm going to make a new pull request so we can do a PR from the restful branch this sunday and include the iframe too.

**Pull request closed without merging**
